make: Human.class student\Student.class teacher\Teacher.class Lab01.class
	
Lab01.class: Lab01.java
	javac Lab01.java
	
teacher\Teacher.class: teacher\Teacher.java
	javac teacher\Teacher.java

student\Student.class: student\Student.java
	javac student\Student.java
	
Human.class: Human.java
	javac Human.java

clean:
	del Lab01.class
	del teacher\Teacher.class
	del student\Student.class
	del Human.class